### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by Megh-Thakkar**
Test for Detail Components view

### CODE REVIEW

**Comment by Megh-Thakkar** [comment]
@rowlandm that does sound like a good idea! I will incorporate the same as soon as possible and then we can merge this PR.

**Comment by rowlandm** [comment]
Remember that you should use >= for some/most of your checks

eg. commits >= 50 as the values should be the same or higher, shouldn't get
lower number of commits in the future.

**Comment by Megh-Thakkar** [comment]
@rowlandm I have updated the tests for the Github API call.

I also added another test to make sure that the 'modified_time' is not before 'created_time'. The test script is incorporated into the .travis.yml file and they have passed according to the repository you specified.

**Comment by Megh-Thakkar** [comment]
Hey @rowlandm can this be merged now as we discussed these changes? Thanks!

**Comment by rowlandm** [comment]
Sure thing.

**Comment by sarthak-sehgal** [comment]
@rowlandm could you please approve the changes? Merging is blocked.

**Pull request merged**
