### PR TITLE
Changed lenght of SlugField:PostgreSQL error

### PR DESCRIPTION
**Pull request by Megh-Thakkar**

### CODE REVIEW

**Comment by rowlandm** [comment]
What happenned? What happens if the URL is greater than 256 chars?

**Comment by DennisSchwartz** [comment]
What does url_name stand for? It's not a URL type field. Interested to know what it's about.

**Comment by Megh-Thakkar** [comment]
@rowlandm, according to the documentation, the maximum length for a SlugField is 255 characters. If a situation arises where the length of a URL is more than that, I will enforce it upon the database. Though, this is extremely rare. Also, since our URLs are homogenous(Github API and NPM), the situation will not arise.

@DennisSchwartz url_name is a Slug formatted name for the components, which will be used to fetch the details(<some_url>/url_name). Basically, if a Component is named as "Component XYZ", the corresponding url_name will be "component-xyz"

**Comment by DennisSchwartz** [comment]
Ah right! That makes a lot of sense. So I guess it will be just truncated if it's too long? Should be fine, I really don't think anyone will give their component such a long name :D

**Comment by Megh-Thakkar** [comment]
Hopefully @DennisSchwartz :P someone had a keyword with length over 75 characters!

**Pull request merged**
